"""Optional plain-English risk narrative, powered by Claude.

The deterministic pipeline (analyzer.py) is the source of truth — it decides what
breaks. This module only *narrates* that verdict: it hands Claude the finished
ImpactReport and asks for a short, human-readable explanation an engineer can drop
into a PR description or read before merging.

It is deliberately additive:
  * Blast Radius runs fully without it (no API key, no `anthropic` install).
  * Claude is never asked to *decide* impact, only to explain the report it's given,
    so it can't override or soften a BREAKING verdict.

Requires the `explain` extra and an Anthropic API key:
    pip install "blast-radius[explain]"
    export ANTHROPIC_API_KEY=sk-ant-...        # or an `ant auth login` profile
"""

from __future__ import annotations

from .models import ImpactReport
from .report import render_markdown

MODEL = "claude-opus-4-8"

SYSTEM_PROMPT = """You are Blast Radius, explaining the impact of a proposed data \
schema change to the engineer about to ship it.

You are given a deterministic impact report generated from DataHub lineage. Your job \
is to explain it in plain English — not to re-decide it. Rules:
- Never contradict the report. If it marks an asset BREAKING, it breaks; do not soften it.
- Lead with the bottom line: is this safe to merge, and if not, what's the single most \
important thing that breaks.
- Then briefly explain the chain of impact (what derives from what) and who owns the \
affected assets, so the reader knows who to talk to.
- Be concrete and cite asset names and owners from the report. No preamble, no \
"Here is...". Keep it under ~180 words. Use short paragraphs or tight bullets."""


def explain_report(
    report: ImpactReport,
    model: str = MODEL,
    api_key: str | None = None,
    max_tokens: int = 1500,
) -> str:
    """Return a plain-English narrative of ``report``, generated by Claude.

    Raises RuntimeError if the `anthropic` package isn't installed. Any API error
    (auth, rate limit, network) propagates to the caller to handle.
    """
    try:
        import anthropic
    except ImportError as exc:
        raise RuntimeError(
            "The explanation layer needs the 'explain' extra: "
            'pip install "blast-radius[explain]"'
        ) from exc

    client = anthropic.Anthropic(api_key=api_key) if api_key else anthropic.Anthropic()

    verdict = "MERGE BLOCKED" if report.is_blocking() else "SAFE TO MERGE"
    user_content = (
        f"Deterministic verdict: {verdict}.\n\n"
        f"Here is the full impact report to explain:\n\n{render_markdown(report, include_graph=False)}"
    )

    message = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_content}],
    )
    return "".join(block.text for block in message.content if block.type == "text").strip()
