"""Migration draft generation.

Turns an ImpactReport into a concrete, owner-addressed migration checklist plus a
best-effort code sketch for each breaking asset. For DROP we flag every reference
for removal; for RENAME we produce find/replace guidance grounded in the real
column names and query text pulled from DataHub.

This is deliberately a *draft* — a starting point for the PR, not an auto-merge.
"""

from __future__ import annotations

from .models import ChangeType, ImpactItem, ImpactReport


def _steps_for(item: ImpactItem, report: ImpactReport) -> list[str]:
    c = report.change
    cols = item.referencing_columns or [c.column]
    steps: list[str] = []

    if c.change_type is ChangeType.RENAME:
        for col in cols:
            steps.append(
                f"Replace references to `{c.column}` with `{c.new_name}` "
                f"(affects column `{col}`)."
            )
    elif c.change_type is ChangeType.RETYPE:
        for col in cols:
            steps.append(
                f"Update casts/assumptions for `{col}` to accommodate type "
                f"`{c.new_type}`; check aggregations and joins."
            )
    else:  # DROP
        for col in cols:
            steps.append(
                f"Remove or re-source `{col}` — its upstream `{c.column}` is being dropped."
            )

    # Attach the real query as context if we have it.
    if item.asset.queries:
        steps.append(f"Definition to update:\n    {item.asset.queries[0].strip()}")
    return steps


def draft_migration(report: ImpactReport) -> str:
    """Produce a Markdown migration plan for all breaking / at-risk assets."""
    c = report.change
    lines: list[str] = [
        "## 🛠️ Migration plan (draft)",
        "",
        f"To ship `{c.describe()}` safely, address the following before merge.",
        "",
    ]

    actionable = report.breaking + report.at_risk
    if not actionable:
        lines.append("_No breaking or at-risk downstream assets — no migration needed._")
        return "\n".join(lines)

    # Group by owner so each person gets a self-contained task list.
    by_owner: dict[str, list[ImpactItem]] = {}
    for item in actionable:
        handles = item.owner_handles or ["@unassigned"]
        for h in handles:
            by_owner.setdefault(h, []).append(item)

    for owner, items in by_owner.items():
        lines.append(f"### {owner}")
        for item in items:
            lines.append(f"- **`{item.asset.name}`** ({item.asset.kind.value})")
            for step in _steps_for(item, report):
                lines.append(f"  - [ ] {step}")
        lines.append("")

    lines += [
        "---",
        "_Draft generated by 💥 Blast Radius. Review before merging — "
        "grounded in DataHub column lineage and query history._",
    ]
    return "\n".join(lines)
